development:
  - name: Staging
    id: staging
    cmd: ganache-cli
    host: http://0.0.0.0
    timeout: 180
    cmd_settings:
      port: 8555
      gas_limit: 12000000
      accounts: 10
      mnemonic: opinion adapt negative bone suit ill fossil alcohol razor script damp fold
      fork: mainnet
