compiler:
  solc:
    optimizer:
      enabled: false
    remappings:
      - "@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@3.2.1-solc-0.7/contracts"
      # - "@UniswapV2/core=Uniswap/uniswap-v2-core@1.0.1/contracts"
      # - "@UniswapV2/periphery=Uniswap/uniswap-v2-periphery@1.0.0-beta.0/contracts"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.2.1-solc-0.7
  # - Uniswap/uniswap-v2-core@1.0.1
  # - Uniswap/uniswap-v2-periphery@1.0.0-beta.0
