compiler:
  solc:
    optimizer:
      enabled: false
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.1/contracts"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.1
