compiler:
  solc:
    optimizer:
      enabled: false
    remappings:
      - "@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7/contracts"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0-solc-0.7
