compiler:
  solc:
    optimizer:
      enabled: false
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0-rc.0/contracts"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0-rc.0 
